### ISSUE TITLE
Installation error - Cluster Creation Error

### ISSUE THREAD

**Issue by pakkua80** [dsieradzki/k4prox#23] opened 2022-10-13 06:52 UTC
Hi,

            I have tried testing this a few times on my proxmox cluster but keep getting different type of errors. I am attaching a screenshot of the error that I am facing now. I try to find the log files but not sure where does it keep it. 
![image](https://user-images.githubusercontent.com/2527115/195522441-cc5a223d-17c3-4d35-be2b-431599d2def8.png)

**Comment by pakkua80** [comment] 2022-10-13 07:32
time="2022-10-13T15:29:58+08:00" level=debug
time="2022-10-13T15:29:58+08:00" level=info msg="Received event" CorrelationId=04024666-82e1-4542-bc3c-52a1bae9cb11 Details="[iscsid] service enabled" Name="Setup virtual machine OS" State=finished
time="2022-10-13T15:29:58+08:00" level=info msg="Received event" CorrelationId=c668a5d8-53a4-40a9-8ff5-906851c63b21 Details="VM ID: 102" Name="Install Kubernetes" State=started
time="2022-10-13T15:29:58+08:00" level=info msg="Received event" CorrelationId=ac36818b-8779-4c6b-b7cf-c2b62358c120 Details="VM ID: 100" Name="Install Kubernetes" State=started
time="2022-10-13T15:29:58+08:00" level=info msg="Received event" CorrelationId=db585cff-23a4-440b-abba-399cdddf0507 Details="VM ID: 101" Name="Install Kubernetes" State=started
time="2022-10-13T15:32:02+08:00" level=error msg="cannot close session" error=EOF
time="2022-10-13T15:32:02+08:00" level=info msg="Received event" CorrelationId=c668a5d8-53a4-40a9-8ff5-906851c63b21 Details= Name="Install Kubernetes" State=finished
time="2022-10-13T15:32:02+08:00" level=info msg="Received event" CorrelationId=6eccbb0f-ac91-4933-8488-5cfc3f4909b1 Details="VM ID: 102" Name="Wait for Kubernetes readiness" State=started
time="2022-10-13T15:32:05+08:00" level=error msg="cannot close session" error=EOF
time="2022-10-13T15:32:05+08:00" level=info msg="Received event" CorrelationId=db585cff-23a4-440b-abba-399cdddf0507 Details= Name="Install Kubernetes" State=finished
time="2022-10-13T15:32:05+08:00" level=info msg="Received event" CorrelationId=8d11464a-9e7d-4208-9dd7-27ef8ff12e00 Details="VM ID: 101" Name="Wait for Kubernetes readiness" State=started
time="2022-10-13T15:32:06+08:00" level=error msg="cannot close session" error=EOF
time="2022-10-13T15:32:06+08:00" level=info msg="Received event" CorrelationId=ac36818b-8779-4c6b-b7cf-c2b62358c120 Details= Name="Install Kubernetes" State=finished
time="2022-10-13T15:32:06+08:00" level=info msg="Received event" CorrelationId=75e004e7-a14b-4041-a574-4cfae90696e9 Details="VM ID: 100" Name="Wait for Kubernetes readiness" State=started

**Comment by dsieradzki** [comment] 2022-10-13 08:49
Thank you for the issue. I will try to reproduce this situation. What steps did you have selected on this popup?
![confirm](https://user-images.githubusercontent.com/10297559/195549469-26255673-db2f-4ddc-9c69-15c0f32bad76.PNG)

**Comment by pakkua80** [comment] 2022-10-13 10:42
Hi Dsieradski, 

                I try to run a second time, it did complete with success. I have check the logs, it still spits the same logs 
![195549469-26255673-db2f-4ddc-9c69-15c0f32bad76](https://user-images.githubusercontent.com/2527115/195574525-c85bb854-be34-4dfa-83a0-cfad00a4be4d.png)


Second Time Run 
![image](https://user-images.githubusercontent.com/2527115/195575337-3c1ef04b-515e-4580-88d6-163f105b4f9c.png)

I double check the logs, in fact it was successfully for both just some how the first session got reflected as an "Cluster creation error"

**Comment by dsieradzki** [comment] 2022-10-13 11:11
Ok, I will check it. Thanks.

**Comment by dsieradzki** [comment] 2022-10-13 11:50
Ok, I reproduced this error when I opened the project file in notepad, to "lock" the file. When K4P finished cluster creation, it tries to save kubeconfig, of course, it can't, because if file is locked.

Can you confirm that you opened the project file in a text editor? 

I will fix the application to handle this kind of situation and improve logs.

**Comment by pakkua80** [comment] 2022-10-13 12:06
I did not go through such a complicated steps. I left my laptop running and came back seeing that. Let me try to see if I can reproduce it. If not I will close the case for now. Don't change the code. =)

**Comment by pakkua80** [comment] 2022-10-13 12:11
But if you could print more logs at this early stage , catch as many errors as possible.

**Comment by dsieradzki** [comment] 2022-10-13 12:17
Ok :) I will do some improvements anyway. A problem with the locked file may happen on Windows. These kinds of errors should be logged already, so I will check too.

**Comment by dsieradzki** [comment] 2022-10-13 22:55
I did more tests and I cannot reproduce the issue. Also I have added more logs. For now I will close the issue. If this happen again, maybe we figure out what was the cause thanks to more logs.

**Closed** 2022-10-13 22:56 UTC
